on:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      md: ${{ steps.plan-md.outputs.out }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_vrsion: 1.9.4
      - uses: reproio/terraform-j2md@master
        with:
          version: v0.0.9
      - run: terraform init
      - run: terraform plan -out=plan.tfplan
      - run: echo "out=$(terraform show -json plan.tfplan)" >> "$GITHUB_OUTPUT"
        id: plan-json
      - run: echo "out=$(echo ${{ steps.plan-json.outputs.out }} | terraform-j2md)" >> "$GITHUB_OUTPUT"
        id: plan-md
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: plan
    steps:
      - run: |
          echo ${{ needs.plan.outputs.md }} | gh pr comment ${{ github.event.number }} -F - --edit-last \
          || echo ${{ needs.plan.outputs.md }} | gh pr comment ${{ github.event.number }} -F -
